<a href="https://colab.research.google.com/github/pppyj-m/pppyj/blob/master/torch%E7%BB%83%E4%B9%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [7]:
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [9]:
torch.ones(2,3,4)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [10]:
x = torch.tensor([1.0,2,4,6])
y = torch.tensor([2,3,4,5])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  5.,  8., 11.]),
 tensor([-1., -1.,  0.,  1.]),
 tensor([ 2.,  6., 16., 30.]),
 tensor([0.5000, 0.6667, 1.0000, 1.2000]),
 tensor([1.0000e+00, 8.0000e+00, 2.5600e+02, 7.7760e+03]))